#!/usr/bin/perl

##
## drt library
##
## drt multiplatform development toolkit
##
## ----------------------------------------------------------------------------------
##
## Copyright (C) 2004-2008 Zbyněk Vyškovský
##
## ----------------------------------------------------------------------------------
##
## LICENSE:
##
## This file is part of drt
##
## drt is free software; you can redistribute it and/or modify it under the
## terms of the GNU Lesser General Public License as published by the Free
## Software Foundation; either version 3 of the License, or (at your option)
## any later version.
##
## drt is distributed in the hope that it will be useful, but WITHOUT ANY
## WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
## FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for
## more details.
##
## You should have received a copy of the GNU Lesser General Public License
## along with drt; if not, write to the Free Software Foundation, Inc., 51
## Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
##
## @author	2004-2008 Zbyněk Vyškovský
## @link	mailto:kvr@matfyz.cz
## @link	http://kvr.matfyz.cz/drt/
## @license	http://www.gnu.org/licenses/lgpl.txt GNU Lesser General Public License v3
##

use strict;
use warnings;

use FileHandle;
use File::Copy;
use File::Spec;
use Getopt::Std;


my %opt = (
	d		=> undef,
);


getopts("d:", \%opt);

my $dist = FileHandle->new("dist_full.list", "<")
	or die "failed to open dist_full.list";

while (<$dist>) {
	die "unable to parse $_" unless (m/^(.*):\s*(.*)$/);
	my $dist_full = "$ENV{DR_ROOT}/include/$1";
	my $src_full = "$ENV{DR_ROOT}/src/$2";
	my $dist_mod = (stat($dist_full))[9];
	my $src_mod = (stat($src_full))[9];

	next unless (defined $dist_mod);
	print("!\t$2 : source does not exist\n"), next unless (defined $src_mod);
	if ($dist_mod > $src_mod) {
		print("!\tinclude/$1 src/$2 : destination newer\n");
		system("$opt{d} $dist_full $src_full") if (defined $opt{d});
		next;
	}
}
