#!/bin/bash

function runSubAction
{
	local file
	local sub
	local dir=`echo $1 | sed 's,^\./,,'`
	local destloc=$destsrc/$dir

	echo running for $dir >&2
	if echo "$nocopy" | grep " $dir " > /dev/null; then
		mkdir -p $destloc
		echo 'all slist lslist sblist lsblist no nothing targ_init:' > $destloc/Makefile
	else
		for sub in `make -C $dir -s lsblist`; do
			runSubAction $dir/$sub
		done

		for file in `make -C $dir -s lslist`; do
			[ "$file" != mklist ] || continue
			dfile=$destsrc/$file
			mkdir -p `dirname $dfile`
			perl -e 'while (<>) { if (m,^(#include ")_gen(/.*)$,) { $_ = "${1}local$2\n"; } elsif (m,^/\*drt,) { while (<>) { last if (m,^\s+\*/,) }; $_ = ""; } print($_); }' < $file > $dfile
			[ ! -x "$file" ] || chmod a+x $dfile
		done

		for file in $dir/_build/_gen/*.hxx; do
			[ -f "$file" ] || continue
			dfile=$destloc/local/`basename $file`
			mkdir -p `dirname $dfile`
			perl -e 'while (<>) { if (m,^(#include ")_gen(/.*)$,) { $_ = "${1}local$2\n"; } elsif (m,^/\*.*\*/,) { $_ = ""; } print($_); }' < $file > $dfile
		done

		perl -e 'sub skipSection() { while (defined ($_ = <>)) { last unless (m/^\t/); } } while (defined ($_ = <>)) { X: s/GEN/LOCAL/g; s/^LOCAL=\$\(BUILD_\)_gen/LOCAL=local/; s/ gh_gh//; if (m/^(gh|include Make_gh|lgh:|gmake:)/) { skipSection(); goto X; } elsif (m/\.gen$/) { skipSection(); goto X; } print($_); }' < $dir/Makefile > $destloc/Makefile
	fi
}

if [ $# -lt 1 ]; then
	echo "Usage: $0 dest-dir"
	exit 2
fi
destdir=$1
destsrc=$destdir/src
shift
nocopy=" $* "

for d in *; do
	[ "x$d" != "xsrc" ] || continue
	cp -R -a $d $destdir/$d
done
cd src
runSubAction .
