#!/usr/bin/perl

###
## drt library
##
## drt multiplatform development toolkit
##
## ----------------------------------------------------------------------------------
##
## Copyright (C) 2004-2008 Zbyněk Vyškovský
##
## ----------------------------------------------------------------------------------
##
## LICENSE:
##
## This file is part of drt
##
## drt is free software; you can redistribute it and/or modify it under the
## terms of the GNU Lesser General Public License as published by the Free
## Software Foundation; either version 3 of the License, or (at your option)
## any later version.
##
## drt is distributed in the hope that it will be useful, but WITHOUT ANY
## WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
## FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for
## more details.
##
## You should have received a copy of the GNU Lesser General Public License
## along with drt; if not, write to the Free Software Foundation, Inc., 51
## Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
##
## @copyright	2004-2008 Zbyněk Vyškovský
## @link	mailto:kvr@matfyz.cz
## @link	http://kvr.matfyz.cz/drt/
## @license	http://www.gnu.org/licenses/lgpl.txt GNU Lesser General Public License v3
###

use strict;
use warnings;

use FileHandle;
use Data::Dumper;
use Getopt::Std;

use File::Basename;
use File::Find;
use lib dirname($0)."/perl";
use dr::FileTransaction;
use dr::FileParser;
use dr::ModelStore;
use dr::TagWriter;
use dr::Util qw(tabalign escapeString escapeStringContent convertBool);
use dr::prog::java::JavaGenerator;
use dr::prog::java::JavaOutFileContext;
use dr::prog::java::JavaOutputGenerator;
use dr::prog::gen::CopyGenerator;


our %opts;
our $file_trans;


sub fileToName($$)
{
	my $ns			= shift;
	my $file		= shift;

	$file =~ s/.*\///;
	$ns =~ s/::/\//g;
	return "${ns}/${file}";
}

sub fileToHeader($$)
{
	my $ns			= shift;
	my $file		= shift;

	$file =~ s/.*\///;
	$file =~ s/\./__/g;
	$ns =~ s/::/__/g;
	return "${ns}__${file}__";
}

sub nsToPub($)
{
	my $ns			= shift;
	$ns =~ s/::/_/g;
	$ns = uc($ns);
	return "${ns}_PUB";
}

sub nsToMacro($)
{
	my $ns			= shift;
	$ns =~ s/::/_/g;
	$ns = uc($ns);
	return "${ns}_NS";
}

sub nsToMacroBegin($)
{
	return nsToMacro(shift)."_BEGIN";
}

sub nsToMacroEnd($)
{
	return nsToMacro(shift)."_END";
}

sub readContent($$)
{
	my $fd			= shift;
	my $fin			= shift;

	my $startline = $fd->getContext();

	my $cont = "";
	my $indent;

	my $line = $fd->readLine();
	if ($line =~ m/^(\s*\* ?)(\s+)/) {
		$indent = $2;
	}
	do {
		if ($line =~ m/^\s*\*\*\//s) {
			die "didn't find close $fin block";
		}
		elsif ($line =~ m/^\s*\*\s?$fin\s*$/s) {
			return $cont;
		}
		elsif ($line =~ m/^(\s*\* ?)(.*)$/s) {
			my $l = $2;
			$l = substr($l, length($indent)) if ((defined $indent) && substr($l, 0, length($indent)) eq $indent);
			$cont .= $l;
		}
		else {
			die "unexpected content: $line";
		}
	} while (defined ($line = $fd->readLine()));
	die "didn't find close $fin block starting at $startline";
}

sub readParagraph($)
{
	my $fd			= shift;

	my $startline = $fd->getContext();

	my $cont = "";

	while (defined (my $line = $fd->readLine())) {
		if ($line =~ m/^\s*\*\s+(\S.*)$/s) {
			$cont .= $1;
		}
		elsif ($line =~ m/^\s*\*\s*$/) {
			chomp $cont;
			return $cont;
		}
		else {
			die "unexpected content starting at $startline";
		}
	}
	die "didn't find empty line of paragraph starting at $startline";
}

sub convertToJavaClass
{
	my $classname			= shift;

	$classname =~ s/::/./g;

	return $classname;
}

sub convertToBoolean
{
	my $value			= shift;

	return $value ? "true" : "false";
}

sub escapeJavaTypeValue
{
	my $java_type			= shift;
	my $value			= shift;

	return "${value}L" if ($java_type eq "Long");
	return escapeStringContent($value) if ($java_type eq "String");
	return $value ? "true" : "false" if ($java_type eq "Boolean");
	return $value;
}

sub translateJavaType # translatedString <- importCtx baseModel javaType-string
{
	my $importCtx			= shift;
	my $baseModel			= shift;
	my $javaType			= shift;

	if ($javaType->{type} =~ m/^(\w+)\s*<\s*(.*)\s*>$/) {
		my $structBase = $1;
		my $elementType = $2;
		$importCtx->printOnce("import ".dr::prog::java::JavaGenerator::mapJavaDatastruct($structBase).";\n");
		my $element;
		if ($elementType eq ".") {
			$element = $baseModel;
		}
		else {
			$element = $baseModel->getSubModel($elementType);
		}
		$importCtx->printOnce("import ".$element->getFullDotName().";\n");
		my $elementBasename = $element->getBaseName();
		return "$structBase<$elementBasename>";
	}
	else {
		dr::prog::java::JavaGenerator::mapJavaType($javaType);
	}
}

sub getDataSource($)
{
	my $classdef			= shift;

	return $classdef->checkDrTagHierarchicalValue("datasource") || dr::Util::doDie("failed to find datasource for class $classdef->{name}");
}

sub convertPkType($)
{
	my $model			= shift;

	my @primary = $model->getPrimary();
	if (@primary > 1) {
		return $model->{name}.".Pk";
	}
	else {
		return dr::prog::java::JavaGenerator::mapJavaAttrType($primary[0]);
	}
}

sub generateEntityBeanPart($$$)
{
	my $context			= shift;
	my $java_out			= shift;
	my $model			= shift;

	my $codeCtx			= $java_out->{codeCtx};

	my $classname = $model->{name};
	my $jclassname = $classname; $jclassname =~ s/::/./g;
	my $filename = $jclassname; $filename =~ s/\./\//g;
	my $pkgname = $jclassname; $pkgname =~ s/\.\w+$//;
	my $classonly = $jclassname; $classonly =~ s/^.*\.//g;

	my $dao = $model->checkSubModel("${classname}::Dao");

	$java_out->printSysimport("import javax.persistence.Entity;\n");
	$java_out->printSysimport("import javax.persistence.Table;\n");

	my $clsCtx = $codeCtx->subContext();
	if (defined (my $roleProcessor = ($dao && $dao->checkDrTagValue("roleProcessor")) // $model->checkDrTagValue("roleProcessor"))) {
		$java_out->printSysimport("import dr.dao.RoleProcessorUse;\n");
		$codeCtx->print("\@RoleProcessorUse(roleProcessor = ".convertToJavaClass($roleProcessor).".class)\n");
	}
	$java_out->printSysimport("import dr.meta.FieldRoles;\n");
	$codeCtx->print("\@FieldRoles(".dr::prog::java::JavaGenerator::formatClassRoles($model).")\n");
	$codeCtx->print("\@Entity\n\@Table(name=\"$classonly\")\npublic class $classonly implements java.io.Serializable\n{\n");
	my $inner = $codeCtx->indentContext(1);
	$inner->print(tabalign("private static final long", 32)."serialVersionUID = 1L;\n\n");
	my $nested_out = $java_out->dupWithFileContext($inner->subContext());
	my $pkCtx = $inner->subContext();
	my $pk_attrCtx = $pkCtx->subAfterContext()->indentContext(1);
	my $pk_methodCtx = $pkCtx->subAfterContext()->indentContext(1);
	my $pk_endCtx = $inner->subContext();
	$inner->print("\n");
	my $attrCtx = $inner->subContext();
	$inner->print("\n");
	my $methodCtx = $inner->subContext();

	my @primary = $model->getPrimary();

	my $displayOrder = "";
	my $pkOrder = "";

	foreach my $nested_name (@{$model->getNestedNames()}) {
		#STDERR->print("processing nested $nested_name\n");
		my $nested = $model->checkSubModel("$model->{full}::$nested_name")
			or dr::Util::doDie("failed to load nested class $model->{full}::$nested_name");
		if ($nested->{stype} eq "enum") {
			dr::prog::java::JavaOutputGenerator->new($nested_out)->generateNested($nested);
			$nested_out->printCode("\n");
		}
	}

	my $use_pk = @primary > 1;

	foreach my $attr (@{$model->getAttrs()}) {
		my $primary_level = $attr->getRole()->{primary} ? @primary > 1 : -1;
		if ($attr->{stype} eq "attr") {
			my ( $type, $tagger ) = $attr->getFinalTypeWithTagger();
			my $java_type = dr::prog::java::JavaGenerator::mapJavaAttrType($attr);
			my $method = ucfirst($attr->{name});
			$java_out->printSysimport("import javax.persistence.Column;\n");
			my $tmap = "";
			$tmap .= "\@Column(name=\"".$attr->{name}."\")\n";
			if ($attr->checkDrTagValue("serial")) {
				$java_out->printSysimport("import javax.persistence.GenerationType;\n");
				$java_out->printSysimport("import javax.persistence.GeneratedValue;\n");
				$tmap .= "\@GeneratedValue(strategy=GenerationType.AUTO)\n";
			}
			my $dfl = (defined $attr->{default}) ?
				" = ".escapeJavaTypeValue($java_type, $attr->{default}) :
				(defined $attr->checkDrTagValue("do_mandatory")) ? " = ".escapeJavaTypeValue($java_type, $attr->checkDrTagValue("do_mandatory")) :
				"";
			my $athis = $primary_level > 0 ? "this.pk" : "this";
			my $roles = "";
			foreach my $roleName (qw(req_new req_get req_set req_del)) {
				my $role = $tagger->checkTagValue($roleName) // $model->checkDrTagValue($roleName);
				if (!defined $role) {
					if (!$model->checkDrTagValue("virtual")) {
						dr::Util::doDie("role $roleName not defined for $classname.$attr->{name}");
					}
					else {
						$role = "guest";
					}
				}
				my $x = $roleName;
				$x =~ s/_(.)/\U$1/;
				$roles .= ", $x = \"".escapeString($role)."\"";
			}
			if ($primary_level > 0) {
				$pk_attrCtx->print($tmap.tabalign("public $java_type", 32)."$attr->{name}$dfl;\n");
				$pkOrder .= ", \"".escapeString($attr->{name})."\"";
			}
			elsif ($primary_level == 0) {
				$java_out->printSysimport("import dr.meta.FieldRoles;\n");
				$attrCtx->print("\@FieldRoles(".substr($roles, 2).")\n");
				$java_out->printSysimport("import javax.persistence.Id;\n");
				$attrCtx->print($tmap."\@Id\n".tabalign("protected $java_type", 32)."$attr->{name}$dfl;\n");
				$displayOrder .= ", \"".escapeString($attr->{name})."\"";
			}
			else {
				if (defined (my $logical = $tagger->checkTagValue("logical"))) {
					$java_out->printSysimport("import dr.logical.LogicalUse;\n");
					$attrCtx->print("\@LogicalUse(logical = ".convertToJavaClass($logical).".class)\n");
				}
				if (defined (my $display = $tagger->checkTagValue("display"))) {
					$java_out->printSysimport("import dr.logical.DisplayUse;\n");
					$attrCtx->print("\@DisplayUse(display = \"".escapeString($display)."\")\n");
					$displayOrder .= ", \"".escapeString($attr->{name})."\"";
				}
				$java_out->printSysimport("import dr.meta.FieldRoles;\n");
				$attrCtx->print("\@FieldRoles(".substr($roles, 2).")\n");
				$java_out->printSysimport("import dr.meta.Mandatory;\n");
				$attrCtx->print("\@Mandatory(mandatory = ".convertToBoolean($attr->{mandatory}).")\n");
				$attrCtx->print($tmap.tabalign("protected $java_type", 32)."$attr->{name}$dfl;\n");
			}
			if ($primary_level == 0) {
				$methodCtx->print(tabalign("public $java_type", 32)."getPk()\n{\n\treturn $attr->{name};\n}\n\n");
				$methodCtx->print(tabalign("public void", 32)."setPk($java_type $attr->{name}_)\n{\n\tthis.$attr->{name} = $attr->{name}_;\n}\n\n");
			}
			$methodCtx->print(tabalign("public void", 32)."set$method($java_type $attr->{name}_)\n{\n\t$athis.$attr->{name} = $attr->{name}_;\n}\n\n");
			$methodCtx->print(tabalign("public $java_type", 32)."get$method()\n{\n\treturn $athis.$attr->{name};\n}\n\n");
			if ($primary_level > 0) {
				$pk_methodCtx->print(tabalign("public void", 32)."set$method($java_type $attr->{name}_)\n{\n\tthis.$attr->{name} = $attr->{name}_;\n}\n\n");
				$pk_methodCtx->print(tabalign("public $java_type", 32)."get$method()\n{\n\treturn this.$attr->{name};\n}\n\n");
			}
		}
		elsif ($attr->{stype} eq "child") {
			if ($attr->checkDrTagValue("tied")) {
				my $tied_class = $attr->getAssocTarget();
				$java_out->printAppimport("import ".convertToJavaClass($tied_class->{full}).";\n");
				$java_out->printSysimport("import javax.persistence.OneToMany;\n");
				$java_out->printSysimport("import javax.persistence.JoinColumns;\n");
				$java_out->printSysimport("import javax.persistence.JoinColumn;\n");
				$java_out->printSysimport("import javax.persistence.FetchType;\n");
				$java_out->printSysimport("import javax.persistence.CascadeType;\n");
				$java_out->printSysimport("import java.util.Set;\n");
				my $tmap = "";
				$tmap .= "\@OneToMany(fetch=FetchType.EAGER, cascade=CascadeType.ALL)\n";
				$tmap .= "\@JoinColumns({ ".
				join(", ", map({ "\@JoinColumn(name=\"$_->{name}\")" } $tied_class->getCompos()->expandAssocAttrs())).
				" })\n";
				$attrCtx->print($tmap.tabalign("private Set<$tied_class->{name}>", 32)."$attr->{name};\n\n");
				$methodCtx->print(tabalign("public Set<$tied_class->{name}>", 32)."get".ucfirst($attr->{name})."()\n{\n\treturn $attr->{name};\n}\n\n");
				$methodCtx->print(tabalign("public void", 32)."set".ucfirst($attr->{name})."(Set<$tied_class->{name}> $attr->{name}_)\n{\n\tthis.$attr->{name} = $attr->{name}_;\n}\n\n");
			}
		}
		elsif ($attr->{stype} eq "assoc") {
			my $java_type = dr::prog::java::JavaGenerator::mapJavaAttrType($attr);
			my $method = ucfirst($attr->{name});
			$java_out->printSysimport("import javax.persistence.Column;\n");
			my $tmap = "";
			$tmap .= "\@Column(name=\"".$attr->{name}."\")\n";
			if ($attr->checkDrTagValue("serial")) {
				$java_out->printSysimport("import javax.persistence.GenerationType;\n");
				$java_out->printSysimport("import javax.persistence.GeneratedValue;\n");
				$tmap .= "\@GeneratedValue(strategy=GenerationType.AUTO)\n";
			}
			my $dfl = (defined $attr->{default}) ?
				" = ".escapeJavaTypeValue($java_type, $attr->{default}) :
				(defined $attr->checkDrTagValue("do_mandatory")) ? " = ".escapeJavaTypeValue($java_type, $attr->checkDrTagValue("do_mandatory")) :
				"";
			my $athis = $primary_level > 0 ? "this.pk" : "this";
			if ($primary_level > 0) {
				$pk_attrCtx->print($tmap.tabalign("public $java_type", 32)."$attr->{name}$dfl;\n");
			}
			elsif ($primary_level == 0) {
				$java_out->printSysimport("import javax.persistence.Id;\n");
				$attrCtx->print($tmap."\@Id\n".tabalign("protected $java_type", 32)."$attr->{name}$dfl;\n");
			}
			else {
				$attrCtx->print($tmap.tabalign("protected $java_type", 32)."$attr->{name}$dfl;\n");
			}
			if ($primary_level == 0) {
				$methodCtx->print(tabalign("public $java_type", 32)."getPk()\n{\treturn $attr->{name};\n}\n\n");
				$methodCtx->print(tabalign("public void", 32)."setPk($java_type $attr->{name}_)\n{\tthis.$attr->{name} = $attr->{name}_;\n}\n\n");
			}
			$methodCtx->print(tabalign("public void", 32)."set$method($java_type $attr->{name}_)\n{\n\t$athis.$attr->{name} = $attr->{name}_;\n}\n\n");
			$methodCtx->print(tabalign("public $java_type", 32)."get$method()\n{\n\treturn $athis.$attr->{name};\n}\n\n");
			if ($primary_level > 0) {
				$pk_methodCtx->print(tabalign("public void", 32)."set$method($java_type $attr->{name}_)\n{\n\tthis.$attr->{name} = $attr->{name}_;\n}\n\n");
				$pk_methodCtx->print(tabalign("public $java_type", 32)."get$method()\n{\n\treturn this.$attr->{name};\n}\n\n");
			}
		}
		elsif ($attr->{stype} eq "compos") {
			my $compos = $attr->getAssocTarget();
			my $compos_class = convertToJavaClass($compos->{name});
			my $pktype = convertPkType($compos);
			$java_out->printSysimport("import dr.meta.ComposDef;\n");
			$clsCtx->print("\@ComposDef(clazz = ".$compos->getFullDotName().".class, pkclazz = ".convertPkType($compos).".class, path = \"pk.$attr->{name}\", composKeySetter = \"set".ucfirst($attr->{name})."\")\n");
			$pk_attrCtx->print("\@Column(name=\"$attr->{name}\")\n");
			my $roles = "";
			foreach my $roleName (qw(req_new req_get req_set req_del)) {
				my $role = $attr->checkDrTagValue($roleName) // ($roleName eq "req_set" || $roleName eq "req_new" ? "extreme" : $model->checkDrTagValue($roleName));
				if (!defined $role) {
					if (!$model->checkDrTagValue("virtual")) {
						dr::Util::doDie("role $roleName not defined for $classname.$attr->{name}");
					}
					else {
						$role = "guest";
					}
				}
				my $x = $roleName;
				$x =~ s/_(.)/\U$1/;
				$roles .= ", $x = \"".escapeString($role)."\"";
			}
			$pk_attrCtx->print("\@FieldRoles(".substr($roles, 2).")\n");
			$pk_attrCtx->print(tabalign("public $pktype", 32)."$attr->{name};\n\n");
			$methodCtx->print(tabalign("public void", 32)."set".ucfirst($attr->{name})."($pktype $attr->{name}_)\n{\n\tthis.pk.$attr->{name} = $attr->{name}_;\n}\n\n");
			$methodCtx->print(tabalign("public $pktype", 32)."get".ucfirst($attr->{name})."()\n{\n\treturn this.pk.$attr->{name};\n}\n\n");
			$pkOrder .= ", \"".escapeString($attr->{name})."\"";
			$use_pk = 1;
		}
		else {
			dr::Util::doDie("unknown attribute stype: $attr->{name} -> $attr->{stype}");
		}
	}
	if ($use_pk) {
		$java_out->printSysimport("import javax.persistence.EmbeddedId;\n");
		$java_out->printSysimport("import javax.persistence.Embeddable;\n");
		$java_out->printSysimport("import java.io.Serializable;\n");
		$java_out->printSysimport("import dr.meta.FieldOrder;\n");
		$pkCtx->print("\@FieldOrder(fields = { ".substr($pkOrder, 2)." })\n");
		$pkCtx->print("\@FieldRoles(".dr::prog::java::JavaGenerator::formatClassRoles($model).")\n");
		$pkCtx->print("\@Embeddable\npublic static class Pk implements Serializable\n{\n");
		$pkCtx->print("\t".tabalign("private static final long serialVersionUID", 32)."= 1L;\n\n");
		my $inpkCtx = $pk_endCtx->indentContext(1);
		$inpkCtx->print(tabalign("public", 32)."Pk()\n{\n}\n\n");
		$inpkCtx->print(tabalign("public", 32)."Pk(".join(", ", map({ $_->{stype} eq "compos" ? (convertPkType($_->getAssocTarget())." $_->{name}") : (dr::prog::java::JavaGenerator::mapJavaAttrType($_)." $_->{name}"); } @primary)).")\n");
		$inpkCtx->print("{\n");
		foreach my $pka (@primary) {
			$inpkCtx->print("\t"."this.$pka->{name} = $pka->{name};\n");
		}
		$inpkCtx->print("}\n\n");
		my $hash_cont = "0";
		my $equals_cont = "true";
		foreach my $pka (@primary) {
			$hash_cont = "($hash_cont)*37+($pka->{name} == null ? 0 : $pka->{name}.hashCode())";
			$equals_cont .= " && ($pka->{name} == null ? s.$pka->{name} == null : $pka->{name}.equals(s.$pka->{name}))";
		}
		$inpkCtx->print("\@Override\n".tabalign("public int", 32)."hashCode()\n{\n");
		$inpkCtx->print("\treturn $hash_cont;\n");
		$inpkCtx->print("}\n\n");
		$inpkCtx->print("\@Override\n".tabalign("public boolean", 32)."equals(Object o)\n{\n");
		$inpkCtx->print("\tif (!(o instanceof Pk))\n\t\treturn false;\n\tPk s = (Pk)o;\n");
		$inpkCtx->print("\treturn $equals_cont;\n");
		$inpkCtx->print("}\n\n");
		$pk_endCtx->print("};\n");
		$pk_endCtx->print("\n\@EmbeddedId\n".tabalign("protected Pk", 32)."pk = new Pk();\n\n");
		$methodCtx->print(tabalign("public Pk", 32)."getPk()\n{\n\treturn pk;\n}\n\n");
		$methodCtx->print(tabalign("public void", 32)."setPk(Pk pk_)\n{\n\tthis.pk = pk_;\n}\n\n");
	}
	$codeCtx->print("};\n");

	if (@{$model->{action_list}}) {
		$java_out->printSysimport("import dr.meta.ActionDef;\n");
		$java_out->printSysimport("import dr.meta.ActionDefs;\n");
		my $actions = "";
		foreach my $action (@{$model->{action_list}}) {
			eval {
				my $atext = "name = \"".escapeString($action->{name})."\"";
				if (defined (my $form_actioner = $action->checkDrTagValue("form_actioner"))) {
					$atext .= ", formActioner = \"".escapeString($form_actioner)."\"";
				}
				$atext .= ", reqRole = \"".escapeString($action->getDrTagValue("req_role"))."\"";
				$actions .= ", \@ActionDef($atext)";
				1;
			}
				or dr::Util::doDie("failed to process $model->{full}.$action->{name}:\n$@");
		}
		$clsCtx->print("\@ActionDefs(actions = { ".substr($actions, 2)." })\n");
	}

	if ($displayOrder) {
		$java_out->printSysimport("import dr.meta.FieldOrder;\n");
		$clsCtx->print("\@FieldOrder(fields = { ".substr($displayOrder, 2)." })\n");
	}
}

sub generateEntityBean($$$$)
{
	my $context			= shift;
	my $location			= shift;
	my $classname			= shift;
	my $more			= shift;

	my $jclassname = $classname; $jclassname =~ s/::/./g;
	my $filename = $jclassname; $filename =~ s/\./\//g;
	my $pkgname = $jclassname; $pkgname =~ s/\.\w+$//;
	my $classonly = $jclassname; $classonly =~ s/^.*\.//g;

	return if ($context->{processed}->{$filename});

	my $model = $context->{model_store}->loadModel($location, $classname);

	my $fdbean = $context->{file_trans}->updateChanged($context->{dst_dir}."/$filename.java");
	my $writer = $fdbean->rememberContext();
	$context->{processed}->{$filename} = 1;

	$writer->print("package $pkgname;\n");
	$writer->print("\n");
	my $sysimportCtx = $writer->subContext();
	$writer->print("\n");
	my $appimportCtx = $writer->subContext();

	$writer->print("\n\n");

	my $java_out = dr::prog::java::JavaOutFileContext->new($context->{model_store}, $sysimportCtx, $appimportCtx, $writer);
	generateEntityBeanPart($context, $java_out, $model);

	$context->{file_trans}->closeFile($fdbean);
}

sub generateOperParamList($)
{
	my $oper			= shift;

	return join(", ",
		map({
				my ( $ptype, $ptagger ) = $_->getFinalTypeWithTagger();
				($ptype->{stype} eq "primitive" ? dr::prog::java::JavaGenerator::mapJavaType($ptype) : convertToJavaClass($ptype->{full}))." $_->{name}"
			} @{$oper->{param_list}})
	);
}

sub generateEntityDaoIf($$$$)
{
	my $context			= shift;
	my $location			= shift;
	my $classname			= shift;
	my $more			= shift;

	my $jbaseclassname = $classname; $jbaseclassname =~ s/::/./g;
	my $jclassname = $jbaseclassname."Dao";
	my $pkgname = $jclassname; $pkgname =~ s/\.\w+$//;
	my $classonly = $jclassname; $classonly =~ s/^.*\.//g;
	my $baseclassonly = $jbaseclassname; $baseclassonly =~ s/^.*\.//g;
	my $filename = "$pkgname.dao.${baseclassonly}Dao"; $filename =~ s/\./\//g;

	return if ($context->{processed}->{$filename});

	my $model = $context->{model_store}->loadModel($location, $classname);
	my $dao = $model->checkSubModel("${classname}::Dao");

	my $fddao = $context->{file_trans}->updateChanged($context->{dst_dir}."/$filename.java");
	$context->{processed}->{$filename} = 1;

	$fddao->print("package $pkgname.dao;\n\n");
	my $sysimportCtx = $fddao->rememberContext();
	my $importCtx = $fddao->rememberContext();
	$importCtx->printOnce("import $jbaseclassname;\n");

	$fddao->printIndented("\n\npublic interface $classonly\n{\n");
	$fddao->indent(1);
	my $methodCtx = $fddao->rememberContext();

	$methodCtx->print(tabalign("public void", 32)."insert($baseclassonly obj);\n");
	$methodCtx->print(tabalign("public void", 32)."update($baseclassonly obj);\n");
	$methodCtx->print(tabalign("public void", 32)."remove($baseclassonly obj);\n");
	$methodCtx->print(tabalign("public boolean", 32)."removeByPk(".dr::prog::java::JavaGenerator::getPkTypeName($model)." obj);\n");
	$methodCtx->print("\n");

	$sysimportCtx->printOnce("import java.util.Map;\n");
	$sysimportCtx->printOnce("import java.util.List;\n");
	$importCtx->printOnce("import dr.core.EntityHolder;\n");
	$importCtx->printOnce("import dr.core.AppContext;\n");
	$importCtx->printOnce("import org.springframework.validation.Errors;\n");

	$methodCtx->print(tabalign("public ".dr::prog::java::JavaGenerator::getPkTypeName($model), 32)."importDynamicKey(Map<String, Object> data);\n");
	$methodCtx->print(tabalign("public Map<String, Object>", 32)."exportDynamicData(EntityHolder<$baseclassonly> holder);\n");
	$methodCtx->print(tabalign("public Map<String, Object>", 32)."exportEntityData(EntityHolder<$baseclassonly> holder);\n");
	$methodCtx->print(tabalign("public $baseclassonly", 32)."createDynamic(Errors validationErrors, EntityHolder<?> composition, Map<String, Object> data);\n");
	$methodCtx->print(tabalign("public EntityHolder<$baseclassonly>", 32)."retrieveDynamic(AppContext baseContext, ".dr::prog::java::JavaGenerator::getPkTypeName($model)." pk);\n");
	$methodCtx->print(tabalign("public $baseclassonly", 32)."updateDynamic(Errors validationErrors, EntityHolder<$baseclassonly> roleObject, ".dr::prog::java::JavaGenerator::getPkTypeName($model)." pk, Map<String, Object> updates);\n");
	$methodCtx->print(tabalign("public boolean", 32)."deleteDynamic(AppContext baseContext, ".dr::prog::java::JavaGenerator::getPkTypeName($model)." pk);\n");
	$methodCtx->print(tabalign("public long", 32)."listDynamic(List<EntityHolder<$baseclassonly>> results, EntityHolder<?> composition, Map<String, Object> filter, List<String> sorts, Long start, Long limit);\n");

	#$methodCtx->print("public Collection<EntityHolder<$baseclassonly>> list();\n\n");
	if ($dao) {
		for my $oper (grep({ $_->{name} =~ /^dr\.(\w+)\./ } @{$dao->{oper_list}})) {
			dr::Util::doDie("wrong name for dao operation: $oper->{name}") unless ($oper->{name} =~ m/^dr\.(\w+)\.(\w+)$/);
			my $optype = $1;
			my $opname = $2;
			if ($optype eq "load") {
				if (0) {
					$sysimportCtx->printOnce("import dr.core.EntityHolder;\n");
					$methodCtx->print(tabalign("public EntityHolder<$baseclassonly>", 32)."$opname(".generateOperParamList($oper).");\n\n");
				}
				else {
					$methodCtx->print(tabalign("public $baseclassonly", 32)."$opname(".generateOperParamList($oper).");\n\n");
				}
			}
			elsif ($optype eq "list") {
				my $ret_type = translateJavaType($sysimportCtx, $model, $oper->getReturnTypeWithTagger());
				$methodCtx->print(tabalign("public $ret_type", 32)."$opname(".generateOperParamList($oper).");\n\n");
			}
			elsif ($optype eq "update") {
				my $ret_type = dr::prog::java::JavaGenerator::mapJavaType($oper->getReturnTypeWithTagger());
				$methodCtx->print(tabalign("public $ret_type", 32)."$opname(".generateOperParamList($oper).");\n\n");
			}
			elsif ($optype eq "query") {
				$methodCtx->print(tabalign("public ".dr::prog::java::JavaGenerator::mapJavaType($oper->getReturnTypeWithTagger()), 32)."$opname(".generateOperParamList($oper).");\n\n");
			}
			else {
				dr::Util::doDie("$jbaseclassname.$oper->{name}: unknown dao operation type: $optype");
			}
		}
	}

	$fddao->indent(-1);
	$fddao->print("};\n");

	$context->{file_trans}->closeFile($fddao);
}

sub generateEntityDaoHib($$$$)
{
	my $context			= shift;
	my $location			= shift;
	my $classname			= shift;
	my $more			= shift;

	my $jbaseclassname = $classname; $jbaseclassname =~ s/::/./g;
	my $jclassname = $jbaseclassname."DaoHib";
	my $filename = $jclassname; $filename =~ s/\./\//g;
	my $pkgbase = $jclassname; $pkgbase =~ s/\.\w+$//;
	my $pkgname = $jclassname; $pkgname =~ s/\.\w+$//; $pkgname .= ".perhib";
	my $classonly = $jclassname; $classonly =~ s/^.*\.//g;
	my $baseclassonly = $jbaseclassname; $baseclassonly =~ s/^.*\.//g;

	return if ($context->{processed}->{$filename});

	my $model = $context->{model_store}->loadModel($location, $classname);
	my $dao = $model->checkSubModel("${classname}::Dao");

	my $fddao = $context->{file_trans}->updateChanged($context->{dst_dir}.dr::Util::prependFile("/$filename.java", "perhib/"));
	$context->{processed}->{$filename} = 1;

	$fddao->print("package $pkgname;\n\n");
	my $sysimportCtx = $fddao->rememberContext();
	$sysimportCtx->printOnce("import $jbaseclassname;\n");
	$sysimportCtx->printOnce("import org.hibernate.SessionFactory;\n");
	$sysimportCtx->printOnce("import org.springframework.orm.hibernate3.HibernateTemplate;\n");
	$sysimportCtx->printOnce("import org.springframework.stereotype.Repository;\n");
	$sysimportCtx->printOnce("import org.springframework.transaction.annotation.Propagation;\n");
	$sysimportCtx->printOnce("import org.springframework.transaction.annotation.Transactional;\n");

	my $importCtx = $fddao->rememberContext();

	$fddao->printIndented("\n\n\@Repository\n\@Transactional(readOnly = true)\npublic class $classonly extends dr.core.ContextDao implements $pkgbase.dao.${baseclassonly}Dao\n{\n");
	$fddao->indent(1);
	my $attrCtx = $fddao->rememberContext();
	$fddao->printIndented("\n");
	my $methodCtx = $fddao->rememberContext();

	$fddao->printAt($attrCtx, tabalign("protected HibernateTemplate", 32)."template = null;\n\n");

	$fddao->printAt($methodCtx, tabalign("public void", 32)."setSessionFactory(SessionFactory sessionFactory)\n{\ttemplate = new HibernateTemplate(sessionFactory);\n}\n\n");

	$fddao->printAt($methodCtx, "\@Transactional(readOnly = false, propagation = Propagation.REQUIRED)\n".tabalign("public void", 32)."insert($baseclassonly obj)\n{\n\ttemplate.saveOrUpdate(obj);\n}\n\n");
	$fddao->printAt($methodCtx, "\@Transactional(readOnly = false, propagation = Propagation.REQUIRED)\n".tabalign("public void", 32)."update($baseclassonly obj)\n{\n\ttemplate.saveOrUpdate(obj);\n}\n\n");
	$fddao->printAt($methodCtx, "\@Transactional(readOnly = false, propagation = Propagation.REQUIRED)\n".tabalign("public void", 32)."remove($baseclassonly obj)\n{\n\ttemplate.delete(obj);\n}\n\n");
	$methodCtx->print("\@Transactional(readOnly = false, propagation = Propagation.REQUIRED)\n".tabalign("public boolean", 32)."removeByPk(".dr::prog::java::JavaGenerator::getPkTypeName($model)." pk)\n{\n\treturn template.bulkUpdate(\"DELETE FROM $baseclassonly WHERE ".dr::prog::java::JavaGenerator::getPkFieldName($model)." = ?\", pk) != 0;\n}\n\n");

	$sysimportCtx->printOnce("import java.util.Map;\n");
	$sysimportCtx->printOnce("import java.util.List;\n");
	$importCtx->printOnce("import dr.core.EntityHolder;\n");
	$importCtx->printOnce("import dr.core.AppContext;\n");
	$importCtx->printOnce("import org.springframework.validation.Errors;\n");

	$methodCtx->print(tabalign("public ".dr::prog::java::JavaGenerator::getPkTypeName($model), 32)."importDynamicKey(Map<String, Object> data) { throw new UnsupportedOperationException(\"hibernate dao do not support dynamic operations\"); }\n");
	$methodCtx->print(tabalign("public Map<String, Object>", 32)."exportDynamicData(EntityHolder<$baseclassonly> holder) { throw new UnsupportedOperationException(\"hibernate dao do not support dynamic operations\"); }\n");
	$methodCtx->print(tabalign("public Map<String, Object>", 32)."exportEntityData(EntityHolder<$baseclassonly> holder) { throw new UnsupportedOperationException(\"hibernate dao do not support dynamic operations\"); }\n");
	$methodCtx->print(tabalign("public $baseclassonly", 32)."createDynamic(Errors validationErrors, EntityHolder<?> composition, Map<String, Object> data) { throw new UnsupportedOperationException(\"hibernate dao do not support dynamic operations\"); }\n");
	$methodCtx->print(tabalign("public EntityHolder<$baseclassonly>", 32)."retrieveDynamic(AppContext baseContext, ".dr::prog::java::JavaGenerator::getPkTypeName($model)." pk) { throw new UnsupportedOperationException(\"hibernate dao do not support dynamic operations\"); }\n");
	$methodCtx->print(tabalign("public $baseclassonly", 32)."updateDynamic(Errors validationErrors, EntityHolder<$baseclassonly> roleObject, ".dr::prog::java::JavaGenerator::getPkTypeName($model)." pk, Map<String, Object> updates) { throw new UnsupportedOperationException(\"hibernate dao do not support dynamic operations\"); }\n");
	$methodCtx->print(tabalign("public boolean", 32)."deleteDynamic(AppContext baseContext, ".dr::prog::java::JavaGenerator::getPkTypeName($model)." pk) { throw new UnsupportedOperationException(\"hibernate dao do not support dynamic operations\"); }\n");
	$methodCtx->print(tabalign("public long", 32)."listDynamic(List<EntityHolder<$baseclassonly>> results, EntityHolder<?> composition, Map<String, Object> filter, List<String> sorts, Long start, Long limit) { throw new UnsupportedOperationException(\"hibernate dao do not support dynamic operations\"); }\n");
	$methodCtx->print("\n");

	#$fddao->printAt($methodCtx, "\@SuppressWarnings(\"unchecked\")\n".tabalign("public Collection<EntityHolder<$baseclassonly>>", 32)."list()\n{\n\tCollection<EntityHolder<$baseclassonly>> result = new LinkedList<EntityHolder<$baseclassonly>>();\n\tfor ($baseclassonly obj: (Collection<$baseclassonly>)template.find(\"from $baseclassonly\")) {\n\t\tresult.add(new EntityHolder<$baseclassonly>(obj, role));\n\t}\n\treturn result;\n}\n\n");
	if ($dao) {
		for my $oper (grep({ $_->{name} =~ /^dr\.(\w+)\./ } @{$dao->{oper_list}})) {
			dr::Util::doDie("wrong name for dao operation: $oper->{name}") unless ($oper->{name} =~ m/^dr\.(\w+)\.(\w+)$/);
			my $optype = $1;
			my $opname = $2;
			if ($optype eq "load") {
				if (0) {
					$sysimportCtx->printOnce("import dr.core.EntityHolder;\n");
					$sysimportCtx->printOnce("import java.util.List;\n");
					$methodCtx->print(tabalign("\@SuppressWarnings(\"unchecked\")\npublic EntityHolder<$baseclassonly>", 32)." $opname(".generateOperParamList($oper).")\n{\n");
					my $contCtx = $methodCtx->indentContext(1);
					my $sql = "";
					my $cond = "";
					my $list = "";
					if (defined ($sql = $oper->checkDrTagValue("sql"))) {
						while ($sql =~ m/^(.*?):(\w+)(.*?)$/s) {
							$sql = "$1?$3";
							$list .= ", $2";
						}
					}
					else {
						foreach my $param (@{$oper->{param_list}}) {
							$cond .= " AND $param->{name} = ?";
							$list .= ", $param->{name}";
						}
						$cond = substr($cond, 5);
						$sql = "FROM $baseclassonly WHERE $cond";
					}
					$contCtx->print("List<$baseclassonly> result = template.find(\"".escapeString($sql)."\"$list);\n");
					$contCtx->print("if (result.size() == 0)\n\treturn null;\n");
					$contCtx->print("return new EntityHolder<$baseclassonly>(result.get(0), null);\n");
					$methodCtx->print("}\n\n");
				}
				else {
					$sysimportCtx->printOnce("import java.util.List;\n");
					$methodCtx->print(tabalign("public $baseclassonly", 32)." $opname(".generateOperParamList($oper).")\n{\n");
					my $contCtx = $methodCtx->indentContext(1);
					my $sql = "";
					my $cond = "";
					my $list = "";
					if (defined ($sql = $oper->checkDrTagValue("sql"))) {
						while ($sql =~ m/^(.*?):(\w+)(.*?)$/s) {
							$sql = "$1?$3";
							$list .= ", $2";
						}
					}
					else {
						foreach my $param (@{$oper->{param_list}}) {
							$cond .= " AND $param->{name} = ?";
							$list .= ", $param->{name}";
						}
						$cond = substr($cond, 5);
						$sql = "FROM $baseclassonly WHERE $cond";
					}
					$contCtx->print("\@SuppressWarnings(\"unchecked\")\nList<$baseclassonly> result = template.find(\"".escapeString($sql)."\"$list);\n");
					$contCtx->print("if (result.size() == 0)\n\treturn null;\n");
					$contCtx->print("return result.get(0);\n");
					$methodCtx->print("}\n\n");
				}
			}
			elsif ($optype eq "list") {
				my $ret_type = translateJavaType($sysimportCtx, $model, $oper->getReturnTypeWithTagger());
				$methodCtx->print(tabalign("public $ret_type", 32)."$opname(".generateOperParamList($oper).")\n{\n");
				my $sql = $oper->getDrTagValue("sql");
				my $cond = "";
				my $list = "";
				while ($sql =~ m/^(.*?):(\w+)(.*?)$/s) {
					$sql = "$1?$3";
					$list .= ", $2";
				}
				$methodCtx->print("\t\@SuppressWarnings(\"unchecked\")\n\t$ret_type result = ($ret_type)template.find(\"".escapeString($sql)."\"$list);\n");
				$methodCtx->print("\treturn result;\n");
				$methodCtx->print("}\n\n");
			}
			elsif ($optype eq "update") {
				my $ret_type = dr::prog::java::JavaGenerator::mapJavaType($oper->getReturnTypeWithTagger());
				$methodCtx->print(tabalign("public $ret_type", 32)."$opname(".generateOperParamList($oper).")\n{\n");
				my $sql = $oper->getDrTagValue("sql");
				my $cond = "";
				my $list = "";
				while ($sql =~ m/^(.*?):((\w+\.)*\w+)(.*?)$/s) {
					$sql = "$1?$4";
					$list .= ", $2";
				}
				$methodCtx->print("\ttemplate.bulkUpdate(\"".escapeString($sql)."\"$list);\n");
				$methodCtx->print("}\n\n");
			}
			elsif ($optype eq "query") {
				my $ret_type = dr::prog::java::JavaGenerator::mapJavaType($oper->getReturnTypeWithTagger());
				$methodCtx->print(tabalign("public $ret_type", 32)."$opname(".generateOperParamList($oper).")\n{\n");
				my $sql = $oper->getDrTagValue("sql");
				my $cond = "";
				my $list = "";
				while ($sql =~ m/^(.*?):(\w+)(.*?)$/s) {
					$sql = "$1?$3";
					$list .= ", $2";
				}
				$sysimportCtx->printOnce("import java.util.List;\n");
				$methodCtx->print("\t\@SuppressWarnings(\"rawtypes\")\n\tList result = template.find(\"".escapeString($sql)."\"$list);\n");
				$methodCtx->print("\treturn result.size() == 0 ? null : ($ret_type)result.get(0);\n");
				$methodCtx->print("}\n\n");
			}
			else {
				dr::Util::doDie("$jbaseclassname.$oper->{name}: unknown dao operation type: $optype");
			}
		}
	}

	$fddao->indent(-1);
	$fddao->print("};\n");

	$context->{file_trans}->closeFile($fddao);
}

sub getEjbTransactionParams($$$)
{
	my $oper			= shift;
	my $readOnly_dfl		= shift;
	my $propagation_dfl		= shift;

	my $readOnly = $oper->checkDrTagValue("readOnly") // $readOnly_dfl;
	my $propagation = $oper->checkDrTagValue("propagation") // $propagation_dfl;
	my $args = "";
	#$args .= ", readOnly = ".(convertBool($readOnly) ? "true" : "false") if ($readOnly ne "");
	#$args .= ", propagation = Propagation.$propagation" if ($propagation);
	$args .= ", TransactionAttributeType.$propagation" if ($propagation);
	return $args ? "\@TransactionAttribute(".substr($args, 2).")\n" : "";
}

sub generateEntityDaoJpa($$$$)
{
	my $context			= shift;
	my $location			= shift;
	my $classname			= shift;
	my $more			= shift;

	my $jbaseclassname = $classname; $jbaseclassname =~ s/::/./g;
	my $jclassname = $jbaseclassname."DaoJpa";
	my $filename = $jclassname; $filename =~ s/\./\//g;
	my $pkgbase = $jclassname; $pkgbase =~ s/\.\w+$//;
	my $pkgname = $jclassname; $pkgname =~ s/\.\w+$//; $pkgname .= ".perjpa";
	my $classonly = $jclassname; $classonly =~ s/^.*\.//g;
	my $baseclassonly = $jbaseclassname; $baseclassonly =~ s/^.*\.//g;

	return if ($context->{processed}->{$filename});

	my $model = $context->{model_store}->loadModel($location, $classname);
	my $dao = $model->checkSubModel("${classname}::Dao");

	my $fddao = $context->{file_trans}->updateChanged($context->{dst_dir}.dr::Util::prependFile("/$filename.java", "perjpa/"));
	$context->{processed}->{$filename} = 1;

	$fddao->print("package $pkgname;\n\n");
	my $sysimportCtx = $fddao->rememberContext();
	$sysimportCtx->printOnce("import $jbaseclassname;\n");
	$sysimportCtx->printOnce("import javax.persistence.EntityManager;\n");
	$sysimportCtx->printOnce("import javax.persistence.PersistenceContext;\n");
	#$sysimportCtx->printOnce("import javax.persistence.PersistenceUnit;\n");
	$sysimportCtx->printOnce("import javax.ejb.TransactionAttribute;\n");
	$sysimportCtx->printOnce("import javax.ejb.TransactionAttributeType;\n");
	$sysimportCtx->printOnce("import org.springframework.stereotype.Repository;\n");
	#$sysimportCtx->printOnce("import org.springframework.transaction.annotation.Propagation;\n");
	$sysimportCtx->printOnce("import org.springframework.transaction.annotation.Transactional;\n");

	my $importCtx = $fddao->rememberContext();

	my $transactionUnit = "\@Transactional(\"".getDataSource($dao || $model)."\")\n";

	$fddao->printIndented("\n\n\@Repository\n$transactionUnit\@TransactionAttribute(TransactionAttributeType.SUPPORTS)\npublic class $classonly extends dr.core.ContextDao implements $pkgbase.dao.${baseclassonly}Dao\n{\n");
	$fddao->indent(1);
	my $attrCtx = $fddao->rememberContext();
	$fddao->printIndented("\n");
	my $methodCtx = $fddao->rememberContext();

	$fddao->printAt($attrCtx, "\@PersistenceContext(unitName=\"".getDataSource($dao || $model)."\")\n");
	#$fddao->printAt($attrCtx, "\@PersistenceUnit(name=\"".getDataSource($dao || $model)."\")\n");
	$fddao->printAt($attrCtx, tabalign("protected EntityManager", 32)."em;\n\n");

	$importCtx->printOnce("import dr.dao.RoleDaoAccessJpa;\n");
	$attrCtx->print(tabalign("protected RoleDaoAccessJpa<$baseclassonly>", 32)."roleDaoAccess;\n\n");
	$methodCtx->print(tabalign("public RoleDaoAccessJpa<$baseclassonly>", 32)."getRoleDaoAccess()\n{\n\tif (roleDaoAccess == null)\n\t\troleDaoAccess = new RoleDaoAccessJpa<$baseclassonly>($baseclassonly.class, em);\n\treturn roleDaoAccess;\n}\n\n");

	$fddao->printAt($methodCtx, "\@Override\n$transactionUnit\@TransactionAttribute(TransactionAttributeType.REQUIRED)\n".tabalign("public void", 32)."insert($baseclassonly obj)\n{\n\tem.persist(obj);\n\tem.flush();\n}\n\n");
	$fddao->printAt($methodCtx, "\@Override\n$transactionUnit\@TransactionAttribute(TransactionAttributeType.REQUIRED)\n".tabalign("public void", 32)."update($baseclassonly obj)\n{\n\tem.merge(obj);\n\tem.flush();\n}\n\n");
	$fddao->printAt($methodCtx, "\@Override\n$transactionUnit\@TransactionAttribute(TransactionAttributeType.REQUIRED)\n".tabalign("public void", 32)."remove($baseclassonly obj)\n{\n\tem.remove(obj);\n\tem.flush();\n}\n\n");
	$fddao->printAt($methodCtx, "\@Override\n$transactionUnit\@TransactionAttribute(TransactionAttributeType.REQUIRED)\n".tabalign("public boolean", 32)."removeByPk(".dr::prog::java::JavaGenerator::getPkTypeName($model)." pk)\n{\n\treturn em.createQuery(\"DELETE FROM $baseclassonly obj WHERE obj.".dr::prog::java::JavaGenerator::getPkFieldName($model)." = ?1\").setParameter(1, pk).executeUpdate() != 0;\n}\n\n");

	$sysimportCtx->printOnce("import java.util.Map;\n");
	$sysimportCtx->printOnce("import java.util.List;\n");
	$importCtx->printOnce("import dr.core.EntityHolder;\n");
	$importCtx->printOnce("import dr.core.AppContext;\n");
	$importCtx->printOnce("import org.springframework.validation.Errors;\n");

	$methodCtx->print(tabalign("public ".dr::prog::java::JavaGenerator::getPkTypeName($model), 32)."importDynamicKey(Map<String, Object> data)\n{\n\treturn (".dr::prog::java::JavaGenerator::getPkTypeName($model).")getRoleDaoAccess().importDynamicKey(data);\n}\n\n");
	$methodCtx->print(tabalign("public Map<String, Object>", 32)."exportDynamicData(EntityHolder<$baseclassonly> holder)\n{\n\treturn getRoleDaoAccess().exportDynamicData(holder);\n}\n\n");
	$methodCtx->print(tabalign("public Map<String, Object>", 32)."exportEntityData(EntityHolder<$baseclassonly> holder)\n{\n\treturn getRoleDaoAccess().exportEntityData(holder);\n}\n\n");
	$methodCtx->print("\@Override\n$transactionUnit\@TransactionAttribute(TransactionAttributeType.REQUIRED)\n".tabalign("public $baseclassonly", 32)."createDynamic(Errors validationErrors, EntityHolder<?> composition, Map<String, Object> data)\n{\n\treturn getRoleDaoAccess().createObject(validationErrors, composition, data);\n}\n\n");
	$methodCtx->print(tabalign("public EntityHolder<$baseclassonly>", 32)."retrieveDynamic(AppContext baseContext, ".dr::prog::java::JavaGenerator::getPkTypeName($model)." pk)\n{\n\treturn getRoleDaoAccess().retrieveObject(baseContext, pk);\n}\n\n");
	$methodCtx->print("\@Override\n$transactionUnit\@TransactionAttribute(TransactionAttributeType.REQUIRED)\n".tabalign("public $baseclassonly", 32)."updateDynamic(Errors validationErrors, EntityHolder<$baseclassonly> roleObject, ".dr::prog::java::JavaGenerator::getPkTypeName($model)." pk, Map<String, Object> updates)\n{\n\treturn getRoleDaoAccess().updateObject(validationErrors, roleObject, pk, updates);\n}\n\n");
	$methodCtx->print("\@Override\n$transactionUnit\@TransactionAttribute(TransactionAttributeType.REQUIRED)\n".tabalign("public boolean", 32)."deleteDynamic(AppContext baseContext, ".dr::prog::java::JavaGenerator::getPkTypeName($model)." pk)\n{\n\treturn getRoleDaoAccess().deleteObject(baseContext, pk);\n}\n\n");
	$methodCtx->print(tabalign("public long", 32)."listDynamic(List<EntityHolder<$baseclassonly>> results, EntityHolder<?> composition, Map<String, Object> filter, List<String> sorts, Long start, Long limit)\n{\n\treturn getRoleDaoAccess().listObjects(results, composition, filter, sorts, start, limit);\n}\n\n");

	$methodCtx->print("\n");

	if ($dao) {
		for my $oper (grep({ $_->{name} =~ /^dr\.(\w+)\./ } @{$dao->{oper_list}})) {
			dr::Util::doDie("wrong name for dao operation: $oper->{name}") unless ($oper->{name} =~ m/^dr\.(\w+)\.(\w+)$/);
			my $optype = $1;
			my $opname = $2;
			if ($optype eq "load") {
				if (0) {
					$sysimportCtx->printOnce("import dr.core.EntityHolder;\n");
					$sysimportCtx->printOnce("import java.util.List;\n");
					$methodCtx->print("\@Override\n".tabalign("\@SuppressWarnings(\"unchecked\")\npublic EntityHolder<$baseclassonly>", 32)." $opname(".generateOperParamList($oper).")\n{\n");
					my $contCtx = $methodCtx->indentContext(1);
					my $sql = "";
					my $cond = "";
					my $list = "";
					if (defined ($sql = $oper->checkDrTagValue("sql"))) {
						my $i = 0;
						while ($sql =~ m/^(.*?):(\w+)(.*?)$/s) {
							++$i;
							$sql = "$1?$i$3";
							$list .= ".setParameter($i, $2)";
						}
					}
					else {
						my $i = 0;
						foreach my $param (@{$oper->{param_list}}) {
							++$i;
							$cond .= " AND $param->{name} = ?$i";
							$list .= ".setParameter($i, $param->{name})";
						}
						$cond = substr($cond, 5);
						$sql = "FROM $baseclassonly WHERE $cond";
					}
					$contCtx->print("List<$baseclassonly> result = em.createQuery(\"".escapeString($sql)."\").$list.getResultList();\n");
					$contCtx->print("if (result.size() == 0)\n\treturn null;\n");
					$contCtx->print("return new EntityHolder<$baseclassonly>(result.get(0), null);\n");
					$methodCtx->print("}\n\n");
				}
				else {
					$sysimportCtx->printOnce("import java.util.List;\n");
					$methodCtx->print("\@Override\n".tabalign("public $baseclassonly", 32)."$opname(".generateOperParamList($oper).")\n{\n");
					my $contCtx = $methodCtx->indentContext(1);
					my $sql = "";
					my $cond = "";
					my $list = "";
					if (defined ($sql = $oper->checkDrTagValue("sql"))) {
						my $i = 0;
						while ($sql =~ m/^(.*?):(\w+)(.*?)$/s) {
							++$i;
							$sql = "$1?$i$3";
							$list .= ".setParameter($i, $2)";
						}
					}
					else {
						my $i = 0;
						foreach my $param (@{$oper->{param_list}}) {
							++$i;
							$cond .= " AND $param->{name} = ?$i";
							$list .= ".setParameter($i, $param->{name})";
						}
						$cond = substr($cond, 5);
						$sql = "FROM $baseclassonly WHERE $cond";
					}
					$contCtx->print("\@SuppressWarnings(\"unchecked\")\nList<$baseclassonly> result = em.createQuery(\"".escapeString($sql)."\")$list.getResultList();\n");
					$contCtx->print("if (result.size() == 0)\n\treturn null;\n");
					$contCtx->print("return result.get(0);\n");
					$methodCtx->print("}\n\n");
				}
			}
			elsif ($optype eq "list") {
				my $ret_type = translateJavaType($sysimportCtx, $model, $oper->getReturnTypeWithTagger());
				$methodCtx->print("\@Override\n".tabalign("public $ret_type", 32)."$opname(".generateOperParamList($oper).")\n{\n");
				my $sql = $oper->getDrTagValue("sql");
				my $cond = "";
				my $list = "";
				my $i = 0;
				while ($sql =~ m/^(.*?):(\w+)(.*?)$/s) {
					++$i;
					$sql = "$1?$i$3";
					$list .= ".setParameter($i, $2)";
				}
				$methodCtx->print("\t\@SuppressWarnings(\"unchecked\")\n\t$ret_type result = ($ret_type)em.createQuery(\"".escapeString($sql)."\")$list.getResultList();\n");
				$methodCtx->print("\treturn result;\n");
				$methodCtx->print("}\n\n");
			}
			elsif ($optype eq "update") {
				my $ret_type = dr::prog::java::JavaGenerator::mapJavaType($oper->getReturnTypeWithTagger());
				$methodCtx->print("\@Override\n".getEjbTransactionParams($oper, 0, "REQUIRED")."\n".tabalign("public $ret_type", 32)."$opname(".generateOperParamList($oper).")\n{\n");
				my $sql = $oper->getDrTagValue("sql");
				my $cond = "";
				my $list = "";
				my $i = 0;
				while ($sql =~ m/^(.*?):((\w+\.)*\w+)(.*?)$/s) {
					++$i;
					$sql = "$1?$i$4";
					$list .= ".setParameter($i, $2)";
				}
				$methodCtx->print("\tem.createQuery(\"".escapeString($sql)."\")$list.executeUpdate();\n");
				$methodCtx->print("}\n\n");
			}
			elsif ($optype eq "query") {
				my $ret_type = dr::prog::java::JavaGenerator::mapJavaType($oper->getReturnTypeWithTagger());
				$methodCtx->print("\@Override\n".tabalign("public $ret_type", 32)."$opname(".generateOperParamList($oper).")\n{\n");
				my $sql = $oper->getDrTagValue("sql");
				my $cond = "";
				my $list = "";
				my $i = 0;
				while ($sql =~ m/^(.*?):(\w+)(.*?)$/s) {
					++$i;
					$sql = "$1?$i$3";
					$list .= ".setParameter($i, $2)";
				}
				$sysimportCtx->printOnce("import java.util.List;\n");
				$methodCtx->print("\t\@SuppressWarnings(\"rawtypes\")\n\tList result = em.createQuery(\"".escapeString($sql)."\")$list.getResultList();\n");
				$methodCtx->print("\treturn result.size() == 0 ? null : ($ret_type)result.get(0);\n");
				$methodCtx->print("}\n\n");
			}
			else {
				dr::Util::doDie("$jbaseclassname.$oper->{name}: unknown dao operation type: $optype");
			}
		}
	}

	$fddao->indent(-1);
	$fddao->print("};\n");

	$context->{file_trans}->closeFile($fddao);
}

sub generateFile($$$$)
{
	my $context			= shift;
	my $location			= shift;
	my $classname			= shift;
	my $gens			= shift;

	foreach my $gen (@$gens) {
		$gen =~ m/^(\w+)(:(.*))?$/
			or dr::Util::doDie("failed to match gen element to word(:options)?: $gen");
		$gen = $1; my $more = $2;
		if ($gen eq "entbean") {
			generateEntityBean($context, $location, $classname, $more);
		}
		elsif ($gen eq "daoif") {
			generateEntityDaoIf($context, $location, $classname, $more);
		}
		elsif ($gen eq "daojpa") {
			generateEntityDaoJpa($context, $location, $classname, $more);
		}
		elsif ($gen eq "daohib") {
			generateEntityDaoHib($context, $location, $classname, $more);
		}
		else {
			dr::Util::doDie("unknown gen identifier '$gen' for $classname");
		}
	}
}

sub runFile($$$$)
{
	my $model_store		= shift;
	my $src_dir		= shift;
	my $dst_dir		= shift;
	my $relname		= shift;

	my $err = eval {
		my $processor;
		if ($relname =~ m/\.java$/) {
			$processor = dr::prog::java::JavaGenerator->new($file_trans, $model_store, $dst_dir, $src_dir, $relname);
		}
		else {
			$processor = dr::prog::gen::CopyGenerator->new($file_trans, $model_store, $dst_dir, $src_dir, $relname);
		}
		$processor->process()
			or $file_trans->flush(), 0;
	};
	unless (defined $err) {
		STDERR->print("$src_dir/$relname:0: fatal error occurred: $@");
		return 1;
	}
	return $err;
}

sub runDirectories($$)
{
	my $src_dir		= shift;
	my $dst_dir		= shift;

	$src_dir .= "/" unless ($src_dir =~ m,/$,);
	$dst_dir .= "/" unless ($dst_dir =~ m,/$,);
	my @files;
	find({
			no_chdir		=> 1,
			wanted			=> sub {
				if (m/^(\.\/)?(.*\/|)(.*)\.(java|xml|properties|sql)$/) {
					push(@files, $_);
				}
			},
			preprocess		=> sub {
				return unless ($File::Find::dir eq $src_dir || $File::Find::dir."/" eq $src_dir || $File::Find::dir =~ m,^(.*/)(\w+)$,);
				return @_;
			},
		}, $src_dir);

	my $model_store = dr::ModelStore->new($opts{m});

	my $context = {
		file_trans		=> $file_trans,
		src_dir			=> $src_dir,
		dst_dir			=> $dst_dir,
		processed		=> {},
		model_store		=> $model_store,
	};

	foreach my $fullname (@files) {
		die "wrong name: $fullname" unless (substr($fullname, 0, length($src_dir)) eq $src_dir);
		my $relname = substr($fullname, length($src_dir));
		my $src_mtime = (stat("$src_dir$relname"))[9];
		my $dst_mtime = (stat("$dst_dir$relname"))[9];
		next if (defined $dst_mtime && $src_mtime <= $dst_mtime);
		$dst_mtime = "-" unless (defined $dst_mtime);
		STDERR->print("generate from $src_dir$relname: $src_mtime $dst_mtime\n");
		if ((my $err = runFile($model_store, $src_dir, $dst_dir, $relname)) != 0) {
			return $err;
		}
	}

	if (defined $opts{l}) {
		my $fdlist = FileHandle->new("$opts{l}", "<")
			or die "failed to open $opts{l}: $!";
		while (<$fdlist>) {
			chomp;
			s/\s*(|#.*)$//;
			next unless (length($_));
			m/^(\w+)\s+(\S+)\s+(.*)$/
				or die "gen line does not match 'location class gens': $_";
			my $location = $1;
			my $classname = $2;
			my @gens = split(/\s+/, $3);
			$classname =~ s/\./::/g;
			generateFile($context, $location, $classname, \@gens);
		}
	}

	return 0;
}


getopts('dm:l:', \%opts)
	or exit(2);

$file_trans = dr::FileTransaction->new();
my $err;

if ($opts{d}) {
	die "Usage (dir): $0 -d src-dir dst-dir" unless (@ARGV == 2);
	$err = runDirectories($ARGV[0], $ARGV[1]);
}
else {
	die "Usage (file): $0 src-dir dst-dir file" unless (@ARGV == 3);
	$err = runFile(dr::ModelStore->new($opts{m}), $ARGV[0], $ARGV[1], $ARGV[2]);
}

if ($err == 0) {
	$file_trans->commit();
}
undef $file_trans;
exit($err);
