#!/usr/bin/perl

##
## drt library
##
## drt multiplatform development toolkit
##
## ----------------------------------------------------------------------------------
##
## Copyright (C) 2004-2008 Zbyněk Vyškovský
##
## ----------------------------------------------------------------------------------
##
## LICENSE:
##
## This file is part of drt
##
## drt is free software; you can redistribute it and/or modify it under the
## terms of the GNU Lesser General Public License as published by the Free
## Software Foundation; either version 3 of the License, or (at your option)
## any later version.
##
## drt is distributed in the hope that it will be useful, but WITHOUT ANY
## WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
## FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for
## more details.
##
## You should have received a copy of the GNU Lesser General Public License
## along with drt; if not, write to the Free Software Foundation, Inc., 51
## Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
##
## @author	2004-2008 Zbyněk Vyškovský
## @link	mailto:kvr@matfyz.cz
## @link	http://kvr.matfyz.cz/drt/
## @license	http://www.gnu.org/licenses/lgpl.txt GNU Lesser General Public License v3
##

use strict;
use warnings;

no locale;

if ($#ARGV != 1) {
	die "Usage: $0 oldver newver\n";
}

my %files = ();
while (<STDIN>) {
	chomp;
	$files{"$_"} = 1;
}

my %diffs = ();

open(my $dh, "diff -urN $ARGV[0] $ARGV[1] |") or die "failed to run diff\n";

while (<$dh>) {
	my $print;
	my $out;
	my $old; my $new;
	my $file;

retest:
	next if (m/^Binary files/);
	next if (m/^Files .* differ$/);
	next if (m/^Only in /);
	next if (m/^File .* is a socket while .* is a socket/);

	$out = $_;
	die "unexpected0 line $_" if (!m/^diff -urN /);
	die "unexpected1 failure reading input\n" unless (defined ($_ = <$dh>));
	$out .= $_;
	die "unexpected1 line $_" if (!m/^--- ([^\t]*)\t/);
	$old = $1;
	die "unexpected2 failure reading input\n" unless (defined ($_ = <$dh>));
	$out .= $_;
	die "unexpected2 line $_" if (!m/^\+\+\+ ([^\t]*)\t/);
	$new = $1;

	if (($print = defined $files{$old} || defined $files{$new})) {
		print(STDERR "$new\n");
		$diffs{$new} = $out;
	}

	while (<$dh>) {
		goto retest if (!m/^[-+\\ @]/);
		$diffs{$new} .= $_ if ($print);
	}
}

foreach (sort { $diffs{$a} cmp $diffs{$b} } keys %diffs) {
	print($diffs{$_});
}
